### Random in Numpy

In [1]:
# we can generate array with pseudo random values using random in  numpy

In [2]:
import numpy as np

In [3]:
arr_1 = np.random.randint(10,20,(3,2))

In [4]:
print(arr_1)

[[10 17]
 [16 10]
 [16 12]]


In [5]:
# This selects a random choice number from a given array
arr_2 = np.random.choice([3,5,6,7])

In [6]:
print(arr_2)

3


## Data distribution in Numpy

In [7]:
# Data Distribution is a list of all possible values, and how often each value occurs.

In [8]:
# Random distribution le chai harek array ma occur huna sakne harek random number ko probability specify gareko huncha

In [9]:
x = np.random.choice([1,2,3,4,5],p = [0.1,0.2,0.3,0.4,0.0],size=(100))

In [10]:
print(x)

[3 4 4 4 2 4 4 4 3 3 4 4 3 4 3 2 4 3 4 2 3 1 4 4 4 4 1 2 4 4 3 3 4 3 1 4 1
 2 3 4 4 4 3 4 3 4 4 2 3 2 3 4 4 1 4 3 4 4 3 1 3 1 2 4 1 3 2 3 3 4 4 3 4 3
 4 4 3 4 1 4 2 2 1 1 4 2 2 3 2 4 3 1 3 4 4 3 2 4 1 3]


In [11]:
y = np.random.choice([1,3,4,5], p = [0.4,0.2,0.3,0.1],size=(2,3))

In [12]:
print(y)

[[1 4 4]
 [4 3 3]]


In [13]:
flaty = y.reshape(-1)

In [14]:
print(flaty)

[1 4 4 4 3 3]


In [15]:
print(y)

[[1 4 4]
 [4 3 3]]


In [16]:
reshapey = y.reshape(3,2)

In [17]:
print(reshapey)

[[1 4]
 [4 4]
 [3 3]]


In [18]:
transpose = y.T

In [19]:
print(transpose)

[[1 4]
 [4 3]
 [4 3]]


## Random Permutation

In [20]:
# A permutation refers to an arrangement of elements. e.g. [3, 2, 1] is a permutation of [1, 2, 3] and vice-versa.

In [21]:
arr = np.array([1,2,3,4,5])

In [22]:
np.random.shuffle(arr)

In [23]:
print(arr)

[2 5 1 4 3]


In [24]:
arr2 = np.array([1,2,3,4,5])

In [25]:
print(np.random.permutation(arr2))
print(arr2)

[1 2 4 3 5]
[1 2 3 4 5]


In [26]:
# shuffle makes changes to the orginal array whereas permutation randomly shuffles the array without making any changes to orgina; array

## Numpy Ufunc

In [27]:
#ufuncs stands for "Universal Functions" and they are NumPy functions that operate on the ndarray object.

In [28]:
# Old Pythonic way for adding two different iterables
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = []

for i, j in zip(x, y):
  z.append(i + j)
print(z)

[5, 7, 9, 11]


In [29]:
# using numpy we can use add() function in order to add these

In [30]:
z = np.add(x,y)

In [31]:
print(z)

[ 5  7  9 11]


In [32]:
def myadd(x, y):
  return x+y

myadd = np.frompyfunc(myadd, 2, 1)

print(myadd([1, 2, 3, 4], [5, 6, 7, 8]))

[6 8 10 12]


In [33]:
print(type(np.add))

<class 'numpy.ufunc'>


In [34]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 6, 8, 2, 33])

newarr = np.power(arr1, arr2)

print(newarr)

[      1000    3200000  729000000 -520093696       2500          0]


In [35]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.mod(arr1, arr2)

print(newarr)

[ 1  6  3  0  0 27]


In [36]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.remainder(arr1, arr2)

print(newarr)

[ 1  6  3  0  0 27]


In [37]:
# The divmod() function return both the quotient and the the mod. The return value is two arrays, the first array contains the quotient and second array contains the mod.
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.divmod(arr1, arr2)

print(newarr)

(array([ 3,  2,  3,  5, 25,  1], dtype=int32), array([ 1,  6,  3,  0,  0, 27], dtype=int32))


In [38]:
arr = np.array([-1, -2, 1, 2, 3, -4])

newarr = np.absolute(arr)

print(newarr)

[1 2 1 2 3 4]


## Rounding Decimals

In [40]:
arr1 = np.array([-3.1666, 3.6667])

In [42]:
arr2 = np.trunc(arr1)

In [43]:
print(arr2)

[-3.  3.]


In [44]:
# trunc basically rounds the element inside the array close to zero

In [45]:
arr3 = np.fix(arr2)

In [46]:
print(arr3)

[-3.  3.]


In [47]:
# It is same as tranc

In [48]:
arr = np.around(3.1666, 2)

print(arr)

3.17


In [49]:
arr = np.floor([-3.1666, 3.6667])

print(arr)

[-4.  3.]


In [50]:
arr = np.ceil([-3.1666, 3.6667])

print(arr)

[-3.  4.]


In [53]:
arr = np.arange(1, 10, 5)

In [54]:
print(arr)

[1 6]


In [55]:
print(np.log2(arr))

[0.        2.5849625]


In [56]:
arr = np.array([1, 2, 3])

newarr = np.cumsum(arr)

print(newarr)

[1 3 6]
