In [1]:
import numpy as np

### List vs Numpy

In [2]:
from time import process_time

In [3]:
python_list = [ i for i in range(10000)]

In [4]:
start_time = process_time()

In [5]:
python_list = [i+5 for i in python_list ]

In [6]:
end_time = process_time()

In [7]:
print(end_time-start_time)

0.046875


In [8]:
npArray = np.array([i for i in range(10000)])
starttime = process_time()
npArray+=5
endtime = process_time()
print(endtime-starttime)

0.0


## Operations in Numpy Array

In [9]:
# This section shows the basic operations which we can perform in numpy array

In [10]:
list1 = [1,2,3,4,5]

In [11]:
print(list1)

[1, 2, 3, 4, 5]


In [12]:
type(list1)

list

In [13]:
np_array = np.array([1,2,3,4,5])

In [14]:
# elements arent seperated by comma, it is similar to matrixes
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [15]:
# creating one dimensional array

In [17]:
a = np.array([1,2,3,4])

In [18]:
a.shape

(4,)

In [19]:
# this shows that it as (rows,columns)

In [21]:
# creating a two dimensional array
b = np.array([(1,2,3,4),(5,6,7,8)])

In [22]:
b.shape

(2, 4)

In [23]:
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [24]:
c = np.array([(1,2,3,4)],dtype=float)

In [25]:
print(c)

[[1. 2. 3. 4.]]


In [26]:
c.shape

(1, 4)

## Initial Placeholders in Numpy

In [28]:
# create a numpy array with all element zero
x = np.zeros((4,5)) # mention dimension inside the function
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [31]:
# create a numpy array with element one
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [32]:
# array with particular value
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [33]:
# creating identity matrix in numpy
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [34]:
# create a numpy array with random values

In [35]:
b = np.random.random((3,4))

In [36]:
print(b)

[[0.54413889 0.83394561 0.3105222  0.45967044]
 [0.70623196 0.38323053 0.7431477  0.17915905]
 [0.95664156 0.72312519 0.61401515 0.35854763]]


In [37]:
# all the values will be between 0 and 1.

In [38]:
# random values integer array within a specific range i.e., 10-100 range
c = np.random.randint(10,100,(3,5))
print(c)

[[82 33 82 61 86]
 [75 89 12 62 29]
 [11 23 75 35 64]]


In [39]:
# array with evenly spaced values. Range is given as 10,30. We have 5 values and they should be evenly spaced
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [40]:
# array of evenly spaced value -> specifiying the step, the step should be 5
e = np.arange(10,30,5)

In [41]:
print(e)

[10 15 20 25]


In [42]:
# convert a list to a numpy array
list2 = [10,20,30,40,50]
np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

## Analyzing a numpy array

In [43]:
a = np.random.randint(10,90,(5,5))
print(a)

[[67 74 50 76 64]
 [89 80 50 39 31]
 [30 13 80 34 45]
 [48 83 14 13 67]
 [30 71 26 21 83]]


In [45]:
# array dimension
a.shape

(5, 5)

In [46]:
# number of dimension
a.ndim

2

In [47]:
# number of elements in an array
a.size

25

In [48]:
# checking datatype of the values in the array
a.dtype

dtype('int32')

## Mathematical operations on Numpy Array

In [49]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
# It will concat two lists
print(list1+list2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [50]:
a = np.asarray(list1)

In [51]:
b = np.asarray(list2)

In [53]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [54]:
# Alternatively we can do
print(np.add(a,b))

[ 7  9 11 13 15]


In [55]:
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


## Array Manipulation

In [56]:
array = np.random.randint(0,10,(2,3))

In [57]:
print(array)

[[9 6 3]
 [6 2 6]]


In [58]:
array.shape

(2, 3)

In [59]:
# transpose of this matrix
trans = np.transpose(array)

In [60]:
print(trans)

[[9 6]
 [6 2]
 [3 6]]


In [61]:
trans.shape

(3, 2)

In [62]:
trans2 = array.T

In [63]:
print(trans2)
trans2.shape

[[9 6]
 [6 2]
 [3 6]]


(3, 2)

In [64]:
# reshaping an array 
resh = np.random.randint(0,10,(2,3))

In [65]:
print(resh)

[[5 5 3]
 [1 3 5]]


In [66]:
resh.shape

(2, 3)

In [73]:
anotherArray = resh.reshape(3,2)

In [74]:
print(anotherArray)

[[5 5]
 [3 1]
 [3 5]]


In [82]:
# flattening the array
arr = np.array([[1, 2, 3], [4, 5, 6]])
newArr = arr.reshape(-1)
print(arr)
print(newArr)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [75]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [77]:
# changing dataype of an array
arr = np.array([1.1, 2.1, 3.1])
newArr = arr.astype('S')

In [78]:
print(newArr)

[b'1.1' b'2.1' b'3.1']


In [79]:
# Copy vs View in  Numpy
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [80]:
arr2 = np.array([4,5,6,7,8])
x = arr2.view()
arr2[0] = 42
print(arr2)
print(x)

[42  5  6  7  8]
[42  5  6  7  8]


In [81]:
# copy makes a completely new array in memory location whereas view is the same location and changes in view can directly
# effect original array

## Iteration through array

In [87]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
print(arr.shape)
for x in np.nditer(arr):
  print(x)

(3, 2)
1
2
3
4
5
6


In [88]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr.shape)

(2, 2, 2)


In [89]:
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'


In [90]:
# when we add op_dtypes as parameter to nditer, it converts the element datatype as we want

In [91]:
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [92]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 1, 0) 3
(0, 1, 1) 4
(1, 0, 0) 5
(1, 0, 1) 6
(1, 1, 0) 7
(1, 1, 1) 8


In [93]:
# Enumerate means to show index as well as corresponding element side by side

## Joining two arrays

In [94]:
arr1 = np.random.randint(0,10,(2,3))

In [98]:
arr2 = np.random.randint(0,10,(2,3))

In [99]:
arr3 = np.concatenate((arr1,arr2))

In [101]:
print(arr3)

[[7 6 0]
 [0 9 0]
 [8 8 3]
 [1 3 8]]


In [102]:
# Joining two arrays along axis = 1

In [103]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

In [108]:
arr3 = np.concatenate((arr1,arr2),axis=1)

In [109]:
print(arr3)

[[1 2 5 6]
 [3 4 7 8]]


## Numpy Array Splitting

In [110]:
arr = np.array([1,2,3,4,5,6,7])
newarr = np.array_split(arr,3)
print(newarr)

[array([1, 2, 3]), array([4, 5]), array([6, 7])]


In [111]:
# so it basically, a single array into three arrays

In [112]:
arr2 = np.full((5,4),5)

In [113]:
print(arr2)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [114]:
newarr2 = np.array_split(arr2,4)

In [115]:
print(newarr2)

[array([[5, 5, 5, 5],
       [5, 5, 5, 5]]), array([[5, 5, 5, 5]]), array([[5, 5, 5, 5]]), array([[5, 5, 5, 5]])]


In [118]:
newarr2[0]

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

In [119]:
arr3 = np.array([[1,2,3,4,5],[6,7,8,9,0]])

In [120]:
print(arr3)

[[1 2 3 4 5]
 [6 7 8 9 0]]


In [121]:
newarr3 = np.array_split(arr3,3)

In [122]:
print(newarr3)

[array([[1, 2, 3, 4, 5]]), array([[6, 7, 8, 9, 0]]), array([], shape=(0, 5), dtype=int32)]


In [123]:
newarr3 = np.array_split(arr3,3, axis=1)

In [124]:
print(newarr3)

[array([[1, 2],
       [6, 7]]), array([[3, 4],
       [8, 9]]), array([[5],
       [0]])]


In [125]:
print(newarr3[0])

[[1 2]
 [6 7]]


In [126]:
flatarr = newarr3[0].reshape(-1)

In [127]:
print(flatarr)

[1 2 6 7]


## Numpy Searching Arrays

In [128]:
arr = np.array([1,2,3,4,5])

In [129]:
x = np.where(arr==5)

In [130]:
print(x)

(array([4], dtype=int64),)


In [131]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [132]:
y = np.where(arr%2!=0)
print(y)

(array([0, 2, 4, 6], dtype=int64),)


In [133]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


In [134]:
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


In [135]:
# This shows where 2,4,6 should be inserted inside the array

In [136]:
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

[0 1 2 3]


In [137]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]
